# mongod.conf
storage:
  dbPath: C:\Users\ASUS\Desktop\sweet-shop-system\Backend\data
systemLog:
  destination: file
  logAppend: true
  path: C:\Users\ASUS\Desktop\sweet-shop-system\Backend\log\mongod.log
net:
  port: 27017
  bindIp: 127.0.0.1

replication:
  replSetName: rs0
